### ISSUE TITLE
Where is the generated video supposed to be saved?

### ISSUE THREAD

**Issue by erikestany** [camenduru/text-to-video-synthesis-colab#2]
Hi!

Where is the generated video supposed to be saved?

After running the last cell a window of a 0.00 second video appears with the text: /tmp/tmpgv746osq.mp4 but it cannot be played or downloaded.

Thanks.

**Comment by pygymy** [comment]
Same-ish.

Attempt 1: I got this error running the 1st cell using a free colab acc:  
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-gbq 0.17.9 requires pyarrow<10.0dev,>=3.0.0, but you have pyarrow 11.0.0 which is incompatible.

Then I ignored it and ran the 2nd cell with my own custom input (which was 3 sentences) and it crashed due to not enough RAM. 

Attempt 2: I clicked restart and run all, and I'm trying again this time with the default input for the 2nd cell and it outputted this 2 sec video but ... the video playback seems bugged its either just a bunch of green or it changes too purple too, but i cant find the file path where its saved either.

/tmpk55v5ish.mp4

<img width="410" alt="Screenshot 2023-03-19 at 11 34 02 PM" src="https://user-images.githubusercontent.com/109264271/226242985-a5c52d19-ce97-49fa-b5e9-f60d04ed5bcd.png">
<img width="411" alt="Screenshot 2023-03-19 at 11 32 30 PM" src="https://user-images.githubusercontent.com/109264271/226242986-04f3fc23-b012-4995-8e21-9769fdb0d59c.png">

**Comment by camenduru** [comment]
Hi @erikestany 👋 please check this 

![Screenshot 2023-03-20 094558](https://user-images.githubusercontent.com/54370274/226266549-21e33329-e0e0-4b6d-b755-28ac2ce51a2d.png)

**Comment by camenduru** [comment]
Hi @pygymy 👋 maybe codec problem please check this video with same video player
https://user-images.githubusercontent.com/54370274/226266698-7fd23019-c7e7-463f-a1bd-e0010de03078.mp4

**Comment by erikestany** [comment]
Hello,

Yes, it's a codec issue, fixed.

Is there a way to determine the duration of the video? and adjust the rest of the parameters of the generation?

Thank you so much!

**Comment by camenduru** [comment]
please watch this https://www.youtube.com/watch?v=b8D4am73e6I

**Comment by impactcolor** [comment]
Hi! On the Colab linked [here ](https://colab.research.google.com/github/camenduru/text-to-video-synthesis-colab/blob/main/zeroscope_v1_1_320s_text_to_video_colab.ipynb)
There is no option to save video.  Is there a colab with the pipeline you mention above?
@camenduru
